version: '3'
services:
  app:
    build: ./node
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./pgsql:/docker-entrypoint-initdb.d
